use customer_behaviour;

/* Q1. What is the total revenue generated by male vs. female customers ? */
select gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Total revenue Generated for male is more than female

/*Q2. Which customers used a discount but still spent more than average purchase amount ?*/
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM customer
);

-- There are many customers who used a discount but still spent more than average purchase amount 

SELECT * FROM CUSTOMER;

/*Q3. Which are the top 5 products with the highest average review rating*/
SELECT item_purchased, ROUND(AVG(review_rating), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;
/*
Boots	3.82
Gloves	3.86
Hat	    3.8
Sandals	3.84
Skirt	3.78
*/

/*Q4. Campare the average Purchase Amount between Standard and Express Shipping*/
SELECT shipping_type, ROUND(AVG(purchase_amount), 2)
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;

-- Average purchase amount is higher for Express Shipping so Business must focus on Express shipping

/*Q5. Do Subscribed customers spend more ? Compare average spend and total revenue
between subscribers and non subscriberssubscription_status */
select subscription_status from customer;

SELECT subscription_status, 
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc;

-- Total Revenue is more for non Subscribed customers than Subscribed Customers and average spend is almost identical for both

/*Q6. Which 5 products  have the highest percantage of purchases  with discount applied? */
SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100,2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc limit 5;

SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc limit 5;

-- This help to tell which products are purchased heavily on discount

/*Q7. Segment customers into New, Returning, and loyal based on their total number of previous purchases, and show the count of each segment */
WITH customer_type as (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)

SELECT customer_segment, count(*) as "Number of Customer"
FROM customer_type
GROUP BY customer_segment

/*
Loyal	    3116
Returning	701
New	        83
*/

-- Q8. What are the top 3 most purchased products within each category ?
SELECT VERSION();

SELECT * FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,

        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank

    FROM customer
    GROUP BY category, item_purchased
) AS ranked_items

WHERE item_rank <= 3;

/*Are customers who are repeat buyers (more than previous purchases) also likely to subscribe ?*/
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

/*Q10. what is the revenue contributions of each Age group*/

SELECT age_group,
	SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;